'use strict';
const { randomUUID } = require('node:crypto');
const now=()=>new Date().toISOString();
const money=v=>Math.round(Number(v||0)*100)/100;
const receiptNo=()=>`MLH-RCP-${Date.now()}-${Math.floor(Math.random()*10000).toString().padStart(4,'0')}`;

async function createCustomerBillingService(db,auditService,inventoryService){
  async function listCustomers(search=''){const q=`%${String(search).trim()}%`;return db.query(`SELECT c.*,c.opening_due AS opening_balance,COALESCE((SELECT SUM(i.due_amount) FROM invoices i WHERE i.customer_id=c.id),0) invoice_due,COALESCE((SELECT SUM(p.amount) FROM payments p WHERE p.customer_id=c.id AND p.invoice_id IS NULL),0) advance_balance FROM customers c WHERE c.is_active=true AND (c.name ILIKE ? OR COALESCE(c.phone,'') ILIKE ? OR COALESCE(c.gstin,'') ILIKE ?) ORDER BY c.name`,[q,q,q]);}
  async function getCustomer(id){const c=await db.queryOne('SELECT c.*,c.opening_due AS opening_balance FROM customers c WHERE id=?',[id]);return c||null;}
  async function createCustomer(input,userId){if(!String(input.name||'').trim())throw new Error('Customer name is required.');const id=randomUUID(),t=now(),code=`CUST-${Date.now().toString().slice(-8)}`;await db.run(`INSERT INTO customers(id,customer_code,name,phone,email,address,gstin,state,opening_due,credit_limit,notes,is_active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[id,code,String(input.name).trim(),input.phone||null,input.email||null,input.address||null,input.gstin||null,input.state||'West Bengal',money(input.openingBalance),input.creditLimit===''?0:money(input.creditLimit),input.notes||null,true,t,t]);await auditService.log({userId,action:'CREATE_CUSTOMER',entityType:'customer',entityId:id,after:{name:input.name,phone:input.phone||null}});return getCustomer(id);}
  async function getProducts(search=''){const q=`%${String(search).trim()}%`;return db.query(`SELECT p.id,p.sku,p.name,p.selling_price,p.gst_rate,p.hsn_code,u.name unit_name,u.abbreviation unit_abbreviation,COALESCE(i.quantity_on_hand,0) quantity_on_hand FROM products p LEFT JOIN units u ON u.id=p.unit_id LEFT JOIN inventory i ON i.product_id=p.id AND i.variant_id IS NULL WHERE p.is_active=true AND (p.name ILIKE ? OR p.sku ILIKE ?) ORDER BY p.name LIMIT 100`,[q,q]);}
  async function getProduct(id){return db.queryOne(`SELECT p.id,p.sku,p.name,p.selling_price,p.gst_rate,p.hsn_code,u.name unit_name,u.abbreviation unit_abbreviation,COALESCE(i.quantity_on_hand,0) quantity_on_hand FROM products p LEFT JOIN units u ON u.id=p.unit_id LEFT JOIN inventory i ON i.product_id=p.id AND i.variant_id IS NULL WHERE p.id=? AND p.is_active=true`,[id]);}
  async function nextInvoiceNo(){const y=new Date().getFullYear();const r=await db.queryOne('SELECT invoice_number FROM invoices WHERE invoice_number LIKE ? ORDER BY created_at DESC LIMIT 1',[`MLH-${y}-%`]);const n=r?Number(String(r.invoice_number).split('-').pop())+1:1;return `MLH-${y}-${String(n).padStart(5,'0')}`;}
  async function createInvoice(input,userId){
    if(!Array.isArray(input.items)||!input.items.length)throw new Error('At least one product is required.');
    const invoiceId=randomUUID(),invoiceNo=await nextInvoiceNo(),t=now();let subtotal=0,discount=0,taxable=0,cgst=0,sgst=0,igst=0;
    const customer=input.customerId?await getCustomer(input.customerId):null;const billingState=customer?.state||input.walkInState||'West Bengal';const sameState=!billingState||billingState.toLowerCase()==='west bengal';
    const items=input.items.map(x=>{const qty=Number(x.quantity),price=money(x.unitPrice),disc=money(x.discount);if(qty<=0)throw new Error('Quantity must be greater than zero.');const gross=money(qty*price),ld=money(gross*disc/100),tx=money(gross-ld),gst=money(tx*Number(x.gstRate||0)/100);subtotal+=gross;discount+=ld;taxable+=tx;if(sameState){cgst+=gst/2;sgst+=gst/2}else igst+=gst;return{...x,quantity:qty,unitPrice:price,discount:disc,taxableAmount:tx,gstAmount:gst,lineTotal:money(tx+gst)};});
    const before=money(taxable+cgst+sgst+igst),total=money(Math.round(before)),roundOff=money(total-before),paid=money(input.paid);if(paid<0||paid>total)throw new Error('Paid amount must be between 0 and invoice total.');const due=money(total-paid),status=due<=0?'paid':paid>0?'partial':'unpaid';
    await db.transaction(async()=>{await db.run(`INSERT INTO invoices(id,invoice_number,customer_id,invoice_date,status,payment_status,subtotal,discount,taxable_amount,cgst,sgst,igst,round_off,total,paid_amount,due_amount,place_of_supply,notes,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[invoiceId,invoiceNo,customer?.id||null,input.invoiceDate||t,'issued',status,money(subtotal),money(discount),money(taxable),money(cgst),money(sgst),money(igst),roundOff,total,paid,due,billingState,[input.walkInName||input.walkInPhone?`Walk-in: ${input.walkInName||'Customer'}${input.walkInPhone?` · Mobile: ${input.walkInPhone}`:''}${input.walkInWhatsapp?` · WhatsApp: ${input.walkInWhatsapp}`:''}${input.walkInAddress?` · Address: ${input.walkInAddress}`:''}${input.walkInGstin?` · GSTIN: ${input.walkInGstin}`:''}${input.notes?` | ${input.notes}`:''}`:input.notes||null][0],userId,t,t]);
      for(const item of items){const itemCgst=sameState?money(item.gstAmount/2):0,itemSgst=sameState?money(item.gstAmount/2):0,itemIgst=sameState?0:item.gstAmount;await db.run(`INSERT INTO invoice_items(invoice_id,product_id,sku,product_name,quantity,unit_price,discount,gst_rate,hsn,cgst,sgst,igst,line_total) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`,[invoiceId,item.productId,item.sku||null,item.productName,item.quantity,item.unitPrice,item.discount,item.gstRate||0,item.hsnCode||null,itemCgst,itemSgst,itemIgst,item.lineTotal]);if(inventoryService)await inventoryService.recordStockTransaction({productId:item.productId,type:'sale',quantity:item.quantity,reason:`Invoice ${invoiceNo}`,referenceType:'invoice',referenceId:invoiceId,performedBy:userId});}
      if(paid>0)await db.run(`INSERT INTO payments(id,receipt_number,customer_id,invoice_id,payment_date,amount,method,reference_no,received_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`,[randomUUID(),receiptNo(),customer?.id||null,invoiceId,t,paid,String(input.paymentMethod||'CASH').toLowerCase(),input.paymentReference||null,userId,t]);});
    await auditService.log({userId,action:'CREATE_INVOICE',entityType:'invoice',entityId:invoiceId,after:{invoiceNo,total,paid,due}});return getInvoice(invoiceId);
  }
  async function getInvoice(id){const i=await db.queryOne(`SELECT i.*,i.invoice_number AS invoice_no,i.paid_amount AS paid,i.due_amount AS due,UPPER(i.payment_status::text) payment_status,c.name customer_name,c.phone customer_phone,c.address customer_address,c.gstin customer_gstin,c.state customer_state FROM invoices i LEFT JOIN customers c ON c.id=i.customer_id WHERE i.id=?`,[id]);if(!i)return null;return{...i,items:await db.query('SELECT * FROM invoice_items WHERE invoice_id=? ORDER BY id',[id]),payments:await db.query(`SELECT p.*,p.reference_no AS reference,p.payment_date AS paid_at,UPPER(p.method::text) method FROM payments p WHERE invoice_id=? ORDER BY payment_date`,[id])};}
  async function listInvoices(limit=50){return searchInvoices({limit});}
  async function recordPayment(input,userId){const customer=await getCustomer(input.customerId);if(!customer)throw new Error('Customer not found.');let amount=money(input.amount);if(amount<=0)throw new Error('Payment amount must be greater than zero.');const t=now(),method=String(input.method||'CASH').toLowerCase(),reference=input.reference||null,notes=input.notes||null;const requested=input.invoiceId?await getInvoice(input.invoiceId):null;
    await db.transaction(async()=>{const apply=async inv=>{const applied=Math.min(amount,money(inv.due));if(applied<=0)return;await db.run(`INSERT INTO payments(id,receipt_number,customer_id,invoice_id,payment_date,amount,method,reference_no,notes,received_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`,[randomUUID(),receiptNo(),customer.id,inv.id,t,applied,method,reference,notes,userId,t]);const paid=money(Number(inv.paid)+applied),due=money(Number(inv.total)-paid);await db.run('UPDATE invoices SET paid_amount=?,due_amount=?,payment_status=?,updated_at=? WHERE id=?',[paid,due,due<=0?'paid':'partial',t,inv.id]);amount=money(amount-applied);};
      if(requested){if(requested.customer_id!==customer.id)throw new Error('Invoice does not belong to customer.');await apply(requested);}else{const dues=await db.query(`SELECT id,total,paid_amount AS paid,due_amount AS due FROM invoices WHERE customer_id=? AND due_amount>0 ORDER BY invoice_date,id`,[customer.id]);for(const inv of dues){if(amount<=0)break;await apply(inv);}}
      if(amount>0)await db.run(`INSERT INTO payments(id,receipt_number,customer_id,invoice_id,payment_date,amount,method,reference_no,notes,received_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`,[randomUUID(),receiptNo(),customer.id,null,t,amount,method,reference,notes||'Advance payment',userId,t]);});
    await auditService.log({userId,action:'RECORD_PAYMENT',entityType:'customer',entityId:customer.id,after:{amount:input.amount,method}});return customerLedger(customer.id);
  }
  async function customerLedger(customerId){const c=await getCustomer(customerId);if(!c)return null;const invoices=await db.query(`SELECT id,invoice_number AS invoice_no,invoice_date,total,paid_amount AS paid,due_amount AS due,UPPER(payment_status::text) payment_status,created_at FROM invoices WHERE customer_id=? ORDER BY invoice_date,created_at`,[customerId]);const payments=await db.query(`SELECT p.*,p.reference_no AS reference,p.payment_date AS paid_at,UPPER(p.method::text) method,i.invoice_number AS invoice_no FROM payments p LEFT JOIN invoices i ON i.id=p.invoice_id WHERE p.customer_id=? ORDER BY p.payment_date,p.created_at`,[customerId]);const invoiceDue=invoices.reduce((s,x)=>s+Number(x.due||0),0),advance=payments.filter(p=>!p.invoice_id).reduce((s,p)=>s+Number(p.amount||0),0);return{customer:c,invoices,payments,openingBalance:money(c.opening_balance),invoiceDue:money(invoiceDue),advance:money(advance),netOutstanding:money(Number(c.opening_balance)+invoiceDue-advance)};}
  async function searchInvoices(f={}){const where=[],params=[];if(f.q){const q=`%${String(f.q).trim()}%`;where.push(`(i.invoice_number ILIKE ? OR COALESCE(c.name,'') ILIKE ? OR COALESCE(c.phone,'') ILIKE ?)`);params.push(q,q,q);}if(f.status){where.push('UPPER(i.payment_status::text)=?');params.push(String(f.status).toUpperCase());}if(f.from){where.push('i.invoice_date::date>=?');params.push(f.from);}if(f.to){where.push('i.invoice_date::date<=?');params.push(f.to);}params.push(Number(f.limit||100));return db.query(`SELECT i.*,i.invoice_number AS invoice_no,i.paid_amount AS paid,i.due_amount AS due,UPPER(i.payment_status::text) payment_status,c.name customer_name,c.phone customer_phone FROM invoices i LEFT JOIN customers c ON c.id=i.customer_id ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY i.invoice_date DESC,i.created_at DESC LIMIT ?`,params);}
  async function salesSummary(period='day'){const d=new Date(),end=d.toISOString().slice(0,10),start=period==='month'?`${end.slice(0,7)}-01`:end;return db.queryOne(`SELECT COUNT(*) bills,COALESCE(SUM(total),0) sales,COALESCE(SUM(paid_amount),0) paid,COALESCE(SUM(due_amount),0) due,COALESCE((SELECT SUM(amount) FROM payments WHERE payment_date::date BETWEEN ? AND ? AND method='cash'),0) cash,COALESCE((SELECT SUM(amount) FROM payments WHERE payment_date::date BETWEEN ? AND ? AND method='upi'),0) upi FROM invoices WHERE invoice_date::date BETWEEN ? AND ?`,[start,end,start,end,start,end]);}
  async function outstandingReport(){return db.query(`SELECT c.id,c.name,c.phone,c.credit_limit,c.opening_due AS opening_balance,COALESCE(SUM(i.due_amount),0)+c.opening_due-COALESCE((SELECT SUM(p.amount) FROM payments p WHERE p.customer_id=c.id AND p.invoice_id IS NULL),0) total_due FROM customers c LEFT JOIN invoices i ON i.customer_id=c.id WHERE c.is_active=true GROUP BY c.id HAVING COALESCE(SUM(i.due_amount),0)+c.opening_due-COALESCE((SELECT SUM(p.amount) FROM payments p WHERE p.customer_id=c.id AND p.invoice_id IS NULL),0)>0 ORDER BY total_due DESC`);}
  async function stockVsSalesReport(){return db.query(`SELECT p.id,p.sku,p.name,COALESCE(inv.quantity_on_hand,0) quantity_on_hand,COALESCE(SUM(ii.quantity),0) qty_sold,COALESCE(SUM(ii.line_total),0) sales_value FROM products p LEFT JOIN inventory inv ON inv.product_id=p.id AND inv.variant_id IS NULL LEFT JOIN invoice_items ii ON ii.product_id=p.id WHERE p.is_active=true GROUP BY p.id,inv.quantity_on_hand ORDER BY qty_sold DESC,p.name LIMIT 200`);}
  async function dashboardSummary(){return salesSummary('day');}
  return{listCustomers,getCustomer,createCustomer,getProducts,getProduct,createInvoice,getInvoice,listInvoices,recordPayment,customerLedger,searchInvoices,salesSummary,outstandingReport,stockVsSalesReport,dashboardSummary};
}
module.exports={createCustomerBillingService};
