'use strict';
const { randomUUID } = require('node:crypto');
const now = () => new Date().toISOString();
const money = (v) => Math.round(Number(v || 0) * 100) / 100;
function createCustomerBillingService(db, auditService) {
  db.run(`CREATE TABLE IF NOT EXISTS customers (id TEXT PRIMARY KEY,name TEXT NOT NULL,phone TEXT,email TEXT,address TEXT,gstin TEXT,state TEXT DEFAULT 'West Bengal',opening_balance REAL NOT NULL DEFAULT 0,credit_limit REAL,notes TEXT,is_active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`);
  db.run(`CREATE UNIQUE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone) WHERE phone IS NOT NULL AND phone <> ''`);
  db.run(`CREATE TABLE IF NOT EXISTS invoices (id TEXT PRIMARY KEY,invoice_no TEXT NOT NULL UNIQUE,customer_id TEXT REFERENCES customers(id),invoice_date TEXT NOT NULL,subtotal REAL NOT NULL DEFAULT 0,discount REAL NOT NULL DEFAULT 0,taxable_amount REAL NOT NULL DEFAULT 0,cgst REAL NOT NULL DEFAULT 0,sgst REAL NOT NULL DEFAULT 0,igst REAL NOT NULL DEFAULT 0,round_off REAL NOT NULL DEFAULT 0,total REAL NOT NULL DEFAULT 0,paid REAL NOT NULL DEFAULT 0,due REAL NOT NULL DEFAULT 0,payment_status TEXT NOT NULL DEFAULT 'UNPAID',notes TEXT,created_by TEXT REFERENCES users(id),created_at TEXT NOT NULL)`);
  db.run(`CREATE TABLE IF NOT EXISTS invoice_items (id INTEGER PRIMARY KEY AUTOINCREMENT,invoice_id TEXT NOT NULL REFERENCES invoices(id),product_id TEXT NOT NULL REFERENCES products(id),product_name TEXT NOT NULL,sku TEXT,quantity REAL NOT NULL,unit_price REAL NOT NULL,discount REAL NOT NULL DEFAULT 0,gst_rate REAL NOT NULL DEFAULT 0,taxable_amount REAL NOT NULL,gst_amount REAL NOT NULL,line_total REAL NOT NULL)`);
  db.run(`CREATE TABLE IF NOT EXISTS payments (id TEXT PRIMARY KEY,invoice_id TEXT REFERENCES invoices(id),customer_id TEXT REFERENCES customers(id),amount REAL NOT NULL,method TEXT NOT NULL,reference TEXT,notes TEXT,paid_at TEXT NOT NULL,created_by TEXT REFERENCES users(id),created_at TEXT NOT NULL)`);
  function listCustomers(search='') { const q=`%${String(search).trim()}%`; return db.query(`SELECT c.*,COALESCE((SELECT SUM(i.due) FROM invoices i WHERE i.customer_id=c.id),0) invoice_due,COALESCE((SELECT SUM(p.amount) FROM payments p WHERE p.customer_id=c.id AND p.invoice_id IS NULL),0) advance_balance FROM customers c WHERE c.is_active=1 AND (c.name LIKE ? OR COALESCE(c.phone,'') LIKE ? OR COALESCE(c.gstin,'') LIKE ?) ORDER BY c.name COLLATE NOCASE`,[q,q,q]); }
  function getCustomer(id) { return db.queryOne('SELECT * FROM customers WHERE id=?',[id]); }
  function createCustomer(input,userId) { const id=randomUUID(),t=now(); db.run(`INSERT INTO customers(id,name,phone,email,address,gstin,state,opening_balance,credit_limit,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`,[id,String(input.name).trim(),input.phone||null,input.email||null,input.address||null,input.gstin||null,input.state||'West Bengal',money(input.openingBalance),input.creditLimit===''?null:money(input.creditLimit),input.notes||null,t,t]); auditService.log({userId,action:'CREATE_CUSTOMER',entityType:'customer',entityId:id,after:input}); return getCustomer(id); }
  function getProducts(search='') { const q=`%${String(search).trim()}%`; return db.query(`SELECT p.id,p.sku,p.name,p.selling_price,p.gst_rate,p.hsn_code,COALESCE(i.quantity_on_hand,0) quantity_on_hand FROM products p LEFT JOIN inventory i ON i.product_id=p.id AND i.variant_id IS NULL WHERE p.is_active=1 AND (p.name LIKE ? OR p.sku LIKE ?) ORDER BY p.name LIMIT 100`,[q,q]); }
  function getProduct(id) { return db.queryOne(`SELECT p.id,p.sku,p.name,p.selling_price,p.gst_rate,p.hsn_code,COALESCE(i.quantity_on_hand,0) quantity_on_hand FROM products p LEFT JOIN inventory i ON i.product_id=p.id AND i.variant_id IS NULL WHERE p.id=? AND p.is_active=1`,[id]); }
  function nextInvoiceNo() { const y=new Date().getFullYear(); const r=db.queryOne('SELECT invoice_no FROM invoices WHERE invoice_no LIKE ? ORDER BY created_at DESC LIMIT 1',[`MLH-${y}-%`]); const n=r?Number(String(r.invoice_no).split('-').pop())+1:1; return `MLH-${y}-${String(n).padStart(5,'0')}`; }
  function createInvoice(input,userId) { if(!Array.isArray(input.items)||!input.items.length) throw new Error('At least one product is required.'); const invoiceId=randomUUID(),invoiceNo=nextInvoiceNo(),t=now(); let subtotal=0,discount=0,taxable=0,cgst=0,sgst=0,igst=0; const customer=input.customerId?getCustomer(input.customerId):null; const sameState=!customer||!customer.state||customer.state.toLowerCase()==='west bengal'; const items=input.items.map(x=>{ const qty=Number(x.quantity),price=money(x.unitPrice),disc=money(x.discount); if(qty<=0) throw new Error('Quantity must be greater than zero.'); const gross=money(qty*price),ld=money(gross*disc/100),tx=money(gross-ld),gst=money(tx*Number(x.gstRate||0)/100); subtotal+=gross;discount+=ld;taxable+=tx;if(sameState){cgst+=gst/2;sgst+=gst/2}else igst+=gst;return {...x,quantity:qty,unitPrice:price,discount:disc,taxableAmount:tx,gstAmount:gst,lineTotal:money(tx+gst)}; }); const before=money(taxable+cgst+sgst+igst),total=money(Math.round(before)),roundOff=money(total-before),paid=money(input.paid); if(paid<0||paid>total) throw new Error('Paid amount must be between 0 and invoice total.'); const due=money(total-paid),status=due<=0?'PAID':paid>0?'PARTIAL':'UNPAID'; db.transaction(()=>{ db.run(`INSERT INTO invoices(id,invoice_no,customer_id,invoice_date,subtotal,discount,taxable_amount,cgst,sgst,igst,round_off,total,paid,due,payment_status,notes,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[invoiceId,invoiceNo,customer?.id||null,input.invoiceDate||t.slice(0,10),money(subtotal),money(discount),money(taxable),money(cgst),money(sgst),money(igst),roundOff,total,paid,due,status,input.notes||null,userId,t]); for(const item of items) db.run(`INSERT INTO invoice_items(invoice_id,product_id,product_name,sku,quantity,unit_price,discount,gst_rate,taxable_amount,gst_amount,line_total) VALUES(?,?,?,?,?,?,?,?,?,?,?)`,[invoiceId,item.productId,item.productName,item.sku||null,item.quantity,item.unitPrice,item.discount,item.gstRate||0,item.taxableAmount,item.gstAmount,item.lineTotal]); if(paid>0) db.run(`INSERT INTO payments(id,invoice_id,customer_id,amount,method,reference,paid_at,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)`,[randomUUID(),invoiceId,customer?.id||null,paid,input.paymentMethod||'CASH',input.paymentReference||null,t,userId,t]); }); auditService.log({userId,action:'CREATE_INVOICE',entityType:'invoice',entityId:invoiceId,after:{invoiceNo,total,paid,due}}); return getInvoice(invoiceId); }
  function getInvoice(id) { const invoice=db.queryOne(`SELECT i.*,c.name customer_name,c.phone customer_phone,c.address customer_address,c.gstin customer_gstin,c.state customer_state FROM invoices i LEFT JOIN customers c ON c.id=i.customer_id WHERE i.id=?`,[id]); if(!invoice)return null; return {...invoice,items:db.query('SELECT * FROM invoice_items WHERE invoice_id=? ORDER BY id',[id]),payments:db.query('SELECT * FROM payments WHERE invoice_id=? ORDER BY paid_at',[id])}; }
  function listInvoices(limit=50) { return searchInvoices({limit}); }
  function recordPayment(input,userId){ const customer=getCustomer(input.customerId); if(!customer) throw new Error('Customer not found.'); let amount=money(input.amount); if(amount<=0) throw new Error('Payment amount must be greater than zero.'); const t=now(),method=input.method||'CASH',reference=input.reference||null,notes=input.notes||null; const requestedInvoice=input.invoiceId?getInvoice(input.invoiceId):null; db.transaction(()=>{ if(requestedInvoice){ if(requestedInvoice.customer_id!==customer.id) throw new Error('Invoice does not belong to customer.'); const applied=Math.min(amount,money(requestedInvoice.due)); if(applied>0){db.run(`INSERT INTO payments(id,invoice_id,customer_id,amount,method,reference,notes,paid_at,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`,[randomUUID(),requestedInvoice.id,customer.id,applied,method,reference,notes,t,userId,t]); const paid=money(requestedInvoice.paid+applied),due=money(requestedInvoice.total-paid); db.run(`UPDATE invoices SET paid=?,due=?,payment_status=? WHERE id=?`,[paid,due,due<=0?'PAID':'PARTIAL',requestedInvoice.id]); amount=money(amount-applied);} } else { const dues=db.query(`SELECT * FROM invoices WHERE customer_id=? AND due>0 ORDER BY invoice_date,id`,[customer.id]); for(const inv of dues){if(amount<=0)break;const applied=Math.min(amount,money(inv.due));db.run(`INSERT INTO payments(id,invoice_id,customer_id,amount,method,reference,notes,paid_at,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`,[randomUUID(),inv.id,customer.id,applied,method,reference,notes,t,userId,t]);const paid=money(inv.paid+applied),due=money(inv.total-paid);db.run(`UPDATE invoices SET paid=?,due=?,payment_status=? WHERE id=?`,[paid,due,due<=0?'PAID':'PARTIAL',inv.id]);amount=money(amount-applied);} } if(amount>0) db.run(`INSERT INTO payments(id,invoice_id,customer_id,amount,method,reference,notes,paid_at,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`,[randomUUID(),null,customer.id,amount,method,reference,notes||'Advance payment',t,userId,t]); }); auditService.log({userId,action:'RECORD_PAYMENT',entityType:'customer',entityId:customer.id,after:{amount:input.amount,method}}); return customerLedger(customer.id); }
  function customerLedger(customerId){ const c=getCustomer(customerId); if(!c)return null; const invoices=db.query(`SELECT id,invoice_no,invoice_date,total,paid,due,payment_status,created_at FROM invoices WHERE customer_id=? ORDER BY invoice_date,created_at`,[customerId]); const payments=db.query(`SELECT p.*,i.invoice_no FROM payments p LEFT JOIN invoices i ON i.id=p.invoice_id WHERE p.customer_id=? ORDER BY p.paid_at,p.created_at`,[customerId]); const invoiceDue=invoices.reduce((s,x)=>s+Number(x.due||0),0),advance=payments.filter(p=>!p.invoice_id).reduce((s,p)=>s+Number(p.amount||0),0); return {customer:c,invoices,payments,openingBalance:money(c.opening_balance),invoiceDue:money(invoiceDue),advance:money(advance),netOutstanding:money(Number(c.opening_balance)+invoiceDue-advance)}; }
  function searchInvoices(f={}){ const where=[],params=[]; if(f.q){const q=`%${String(f.q).trim()}%`;where.push(`(i.invoice_no LIKE ? OR COALESCE(c.name,'') LIKE ? OR COALESCE(c.phone,'') LIKE ?)`);params.push(q,q,q);} if(f.status){where.push('i.payment_status=?');params.push(f.status);} if(f.from){where.push('i.invoice_date>=?');params.push(f.from);} if(f.to){where.push('i.invoice_date<=?');params.push(f.to);} params.push(Number(f.limit||100)); return db.query(`SELECT i.*,c.name customer_name,c.phone customer_phone FROM invoices i LEFT JOIN customers c ON c.id=i.customer_id ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY i.invoice_date DESC,i.created_at DESC LIMIT ?`,params); }
  function salesSummary(period='day'){ const d=new Date(),end=d.toISOString().slice(0,10),start=period==='month'?`${end.slice(0,7)}-01`:end; return db.queryOne(`SELECT COUNT(*) bills,COALESCE(SUM(total),0) sales,COALESCE(SUM(paid),0) paid,COALESCE(SUM(due),0) due,COALESCE((SELECT SUM(amount) FROM payments WHERE date(paid_at) BETWEEN ? AND ? AND method='CASH'),0) cash,COALESCE((SELECT SUM(amount) FROM payments WHERE date(paid_at) BETWEEN ? AND ? AND method='UPI'),0) upi FROM invoices WHERE invoice_date BETWEEN ? AND ?`,[start,end,start,end,start,end]); }
  function outstandingReport(){ return db.query(`SELECT c.id,c.name,c.phone,c.credit_limit,c.opening_balance,COALESCE(SUM(i.due),0)+c.opening_balance-COALESCE((SELECT SUM(p.amount) FROM payments p WHERE p.customer_id=c.id AND p.invoice_id IS NULL),0) total_due FROM customers c LEFT JOIN invoices i ON i.customer_id=c.id WHERE c.is_active=1 GROUP BY c.id HAVING total_due>0 ORDER BY total_due DESC`); }
  function stockVsSalesReport(){ return db.query(`SELECT p.id,p.sku,p.name,COALESCE(inv.quantity_on_hand,0) quantity_on_hand,COALESCE(SUM(ii.quantity),0) qty_sold,COALESCE(SUM(ii.line_total),0) sales_value FROM products p LEFT JOIN inventory inv ON inv.product_id=p.id AND inv.variant_id IS NULL LEFT JOIN invoice_items ii ON ii.product_id=p.id WHERE p.is_active=1 GROUP BY p.id ORDER BY qty_sold DESC,p.name LIMIT 200`); }
  function dashboardSummary() { return salesSummary('day'); }
  return {listCustomers,getCustomer,createCustomer,getProducts,getProduct,createInvoice,getInvoice,listInvoices,recordPayment,customerLedger,searchInvoices,salesSummary,outstandingReport,stockVsSalesReport,dashboardSummary};
}
module.exports={createCustomerBillingService};
