'use strict';
const { randomUUID } = require('node:crypto');
const now = () => new Date().toISOString();
const money = (v) => Math.round(Number(v || 0) * 100) / 100;
function createCustomerBillingService(db, auditService) {
  db.run(`CREATE TABLE IF NOT EXISTS customers (id TEXT PRIMARY KEY,name TEXT NOT NULL,phone TEXT,email TEXT,address TEXT,gstin TEXT,state TEXT DEFAULT 'West Bengal',opening_balance REAL NOT NULL DEFAULT 0,credit_limit REAL,notes TEXT,is_active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`);
  db.run(`CREATE UNIQUE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone) WHERE phone IS NOT NULL AND phone <> ''`);
  db.run(`CREATE TABLE IF NOT EXISTS invoices (id TEXT PRIMARY KEY,invoice_no TEXT NOT NULL UNIQUE,customer_id TEXT REFERENCES customers(id),invoice_date TEXT NOT NULL,subtotal REAL NOT NULL DEFAULT 0,discount REAL NOT NULL DEFAULT 0,taxable_amount REAL NOT NULL DEFAULT 0,cgst REAL NOT NULL DEFAULT 0,sgst REAL NOT NULL DEFAULT 0,igst REAL NOT NULL DEFAULT 0,round_off REAL NOT NULL DEFAULT 0,total REAL NOT NULL DEFAULT 0,paid REAL NOT NULL DEFAULT 0,due REAL NOT NULL DEFAULT 0,payment_status TEXT NOT NULL DEFAULT 'UNPAID',notes TEXT,created_by TEXT REFERENCES users(id),created_at TEXT NOT NULL)`);
  db.run(`CREATE TABLE IF NOT EXISTS invoice_items (id INTEGER PRIMARY KEY AUTOINCREMENT,invoice_id TEXT NOT NULL REFERENCES invoices(id),product_id TEXT NOT NULL REFERENCES products(id),product_name TEXT NOT NULL,sku TEXT,quantity REAL NOT NULL,unit_price REAL NOT NULL,discount REAL NOT NULL DEFAULT 0,gst_rate REAL NOT NULL DEFAULT 0,taxable_amount REAL NOT NULL,gst_amount REAL NOT NULL,line_total REAL NOT NULL)`);
  db.run(`CREATE TABLE IF NOT EXISTS payments (id TEXT PRIMARY KEY,invoice_id TEXT REFERENCES invoices(id),customer_id TEXT REFERENCES customers(id),amount REAL NOT NULL,method TEXT NOT NULL,reference TEXT,notes TEXT,paid_at TEXT NOT NULL,created_by TEXT REFERENCES users(id),created_at TEXT NOT NULL)`);
  function listCustomers(search='') { const q=`%${String(search).trim()}%`; return db.query(`SELECT c.*,COALESCE((SELECT SUM(i.due) FROM invoices i WHERE i.customer_id=c.id),0) invoice_due FROM customers c WHERE c.is_active=1 AND (c.name LIKE ? OR COALESCE(c.phone,'') LIKE ? OR COALESCE(c.gstin,'') LIKE ?) ORDER BY c.name COLLATE NOCASE`,[q,q,q]); }
  function getCustomer(id) { return db.queryOne('SELECT * FROM customers WHERE id=?',[id]); }
  function createCustomer(input,userId) { const id=randomUUID(),t=now(); db.run(`INSERT INTO customers(id,name,phone,email,address,gstin,state,opening_balance,credit_limit,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`,[id,String(input.name).trim(),input.phone||null,input.email||null,input.address||null,input.gstin||null,input.state||'West Bengal',money(input.openingBalance),input.creditLimit===''?null:money(input.creditLimit),input.notes||null,t,t]); auditService.log({userId,action:'CREATE_CUSTOMER',entityType:'customer',entityId:id,after:input}); return getCustomer(id); }
  function getProducts(search='') { const q=`%${String(search).trim()}%`; return db.query(`SELECT p.id,p.sku,p.name,p.selling_price,p.gst_rate,p.hsn_code,COALESCE(i.quantity_on_hand,0) quantity_on_hand FROM products p LEFT JOIN inventory i ON i.product_id=p.id AND i.variant_id IS NULL WHERE p.is_active=1 AND (p.name LIKE ? OR p.sku LIKE ?) ORDER BY p.name LIMIT 100`,[q,q]); }
  function getProduct(id) { return db.queryOne(`SELECT p.id,p.sku,p.name,p.selling_price,p.gst_rate,p.hsn_code,COALESCE(i.quantity_on_hand,0) quantity_on_hand FROM products p LEFT JOIN inventory i ON i.product_id=p.id AND i.variant_id IS NULL WHERE p.id=? AND p.is_active=1`,[id]); }
  function nextInvoiceNo() { const y=new Date().getFullYear(); const r=db.queryOne('SELECT invoice_no FROM invoices WHERE invoice_no LIKE ? ORDER BY created_at DESC LIMIT 1',[`MLH-${y}-%`]); const n=r?Number(String(r.invoice_no).split('-').pop())+1:1; return `MLH-${y}-${String(n).padStart(5,'0')}`; }
  function createInvoice(input,userId) {
    if(!Array.isArray(input.items)||!input.items.length) throw new Error('At least one product is required.');
    const invoiceId=randomUUID(),invoiceNo=nextInvoiceNo(),t=now(); let subtotal=0,discount=0,taxable=0,cgst=0,sgst=0,igst=0;
    const customer=input.customerId?getCustomer(input.customerId):null; const sameState=!customer||!customer.state||customer.state.toLowerCase()==='west bengal';
    const items=input.items.map(x=>{ const qty=Number(x.quantity),price=money(x.unitPrice),disc=money(x.discount); if(qty<=0) throw new Error('Quantity must be greater than zero.'); const gross=money(qty*price),ld=money(gross*disc/100),tx=money(gross-ld),gst=money(tx*Number(x.gstRate||0)/100); subtotal+=gross;discount+=ld;taxable+=tx;if(sameState){cgst+=gst/2;sgst+=gst/2}else igst+=gst;return {...x,quantity:qty,unitPrice:price,discount:disc,taxableAmount:tx,gstAmount:gst,lineTotal:money(tx+gst)}; });
    const before=money(taxable+cgst+sgst+igst),total=money(Math.round(before)),roundOff=money(total-before),paid=money(input.paid); if(paid<0||paid>total) throw new Error('Paid amount must be between 0 and invoice total.'); const due=money(total-paid),status=due<=0?'PAID':paid>0?'PARTIAL':'UNPAID';
    db.transaction(()=>{ db.run(`INSERT INTO invoices(id,invoice_no,customer_id,invoice_date,subtotal,discount,taxable_amount,cgst,sgst,igst,round_off,total,paid,due,payment_status,notes,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[invoiceId,invoiceNo,customer?.id||null,input.invoiceDate||t.slice(0,10),money(subtotal),money(discount),money(taxable),money(cgst),money(sgst),money(igst),roundOff,total,paid,due,status,input.notes||null,userId,t]); for(const item of items) db.run(`INSERT INTO invoice_items(invoice_id,product_id,product_name,sku,quantity,unit_price,discount,gst_rate,taxable_amount,gst_amount,line_total) VALUES(?,?,?,?,?,?,?,?,?,?,?)`,[invoiceId,item.productId,item.productName,item.sku||null,item.quantity,item.unitPrice,item.discount,item.gstRate||0,item.taxableAmount,item.gstAmount,item.lineTotal]); if(paid>0) db.run(`INSERT INTO payments(id,invoice_id,customer_id,amount,method,reference,paid_at,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)`,[randomUUID(),invoiceId,customer?.id||null,paid,input.paymentMethod||'CASH',input.paymentReference||null,t,userId,t]); });
    auditService.log({userId,action:'CREATE_INVOICE',entityType:'invoice',entityId:invoiceId,after:{invoiceNo,total,paid,due}}); return getInvoice(invoiceId);
  }
  function getInvoice(id) { const invoice=db.queryOne(`SELECT i.*,c.name customer_name,c.phone customer_phone,c.address customer_address,c.gstin customer_gstin,c.state customer_state FROM invoices i LEFT JOIN customers c ON c.id=i.customer_id WHERE i.id=?`,[id]); if(!invoice)return null; return {...invoice,items:db.query('SELECT * FROM invoice_items WHERE invoice_id=? ORDER BY id',[id]),payments:db.query('SELECT * FROM payments WHERE invoice_id=? ORDER BY paid_at',[id])}; }
  function listInvoices(limit=50) { return db.query(`SELECT i.*,c.name customer_name FROM invoices i LEFT JOIN customers c ON c.id=i.customer_id ORDER BY i.created_at DESC LIMIT ?`,[limit]); }
  function dashboardSummary() { const d=new Date().toISOString().slice(0,10); return db.queryOne(`SELECT COUNT(*) bills,COALESCE(SUM(total),0) sales,COALESCE(SUM(paid),0) paid,COALESCE(SUM(due),0) due FROM invoices WHERE invoice_date=?`,[d]); }
  return {listCustomers,getCustomer,createCustomer,getProducts,getProduct,createInvoice,getInvoice,listInvoices,dashboardSummary};
}
module.exports={createCustomerBillingService};
