import Link from 'next/link';
import { getApp } from '@/lib/db';
import { requireAdmin } from '@/lib/session';
import PrintButton from '@/components/admin/PrintButton';
export default function InvoicePage({params}:{params:{id:string}}){
  requireAdmin(); const invoice=getApp().customerBillingService.getInvoice(params.id); if(!invoice) return <div className="rounded-2xl bg-white p-8 text-center">Invoice not found.</div>;
  return <div className="mx-auto max-w-4xl space-y-4"><div className="flex items-center justify-between"><Link href="/admin/billing" className="text-sm font-bold text-[#07527f]">← New bill</Link><PrintButton/></div>
    <article className="rounded-2xl border bg-white p-6 shadow-sm print:border-0 print:shadow-none sm:p-8"><header className="flex flex-col justify-between gap-4 border-b pb-5 sm:flex-row"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#07527f]">MAA LAXMI HARDWARE</p><h1 className="mt-1 text-2xl font-black">Tax Invoice</h1><p className="text-xs text-slate-500">Invoice No: <b>{invoice.invoice_no}</b></p></div><div className="text-left text-sm sm:text-right"><p>{invoice.invoice_date}</p><p className="mt-1 font-bold">{invoice.payment_status}</p></div></header>
    <section className="grid gap-4 border-b py-5 sm:grid-cols-2"><div><p className="text-[10px] font-bold uppercase text-slate-400">Bill To</p><p className="mt-1 font-bold">{invoice.customer_name||'Walk-in Customer'}</p><p className="text-sm text-slate-600">{invoice.customer_address||''}</p><p className="text-sm">{invoice.customer_phone||''}</p></div><div className="sm:text-right"><p className="text-[10px] font-bold uppercase text-slate-400">GSTIN</p><p className="mt-1 font-mono text-sm">{invoice.customer_gstin||'—'}</p></div></section>
    <table className="w-full text-sm"><thead className="border-b text-left text-xs uppercase text-slate-500"><tr><th className="py-3">Item</th><th className="py-3 text-right">Qty</th><th className="py-3 text-right">Rate</th><th className="py-3 text-right">GST</th><th className="py-3 text-right">Total</th></tr></thead><tbody className="divide-y">{invoice.items.map((x:any)=><tr key={x.id}><td className="py-3 font-semibold">{x.product_name}<div className="font-mono text-[10px] text-slate-400">{x.sku||''}</div></td><td className="py-3 text-right">{x.quantity}</td><td className="py-3 text-right">₹{Number(x.unit_price).toFixed(2)}</td><td className="py-3 text-right">{x.gst_rate}%</td><td className="py-3 text-right font-bold">₹{Number(x.line_total).toFixed(2)}</td></tr>)}</tbody></table>
    <section className="ml-auto max-w-sm space-y-2 border-t pt-4 text-sm"><div className="flex justify-between"><span>Taxable amount</span><b>₹{Number(invoice.taxable_amount).toFixed(2)}</b></div><div className="flex justify-between"><span>CGST + SGST</span><b>₹{(Number(invoice.cgst)+Number(invoice.sgst)).toFixed(2)}</b></div><div className="flex justify-between"><span>IGST</span><b>₹{Number(invoice.igst).toFixed(2)}</b></div><div className="flex justify-between"><span>Round off</span><b>₹{Number(invoice.round_off).toFixed(2)}</b></div><div className="flex justify-between border-t pt-3 text-lg"><span className="font-black">Grand Total</span><b>₹{Number(invoice.total).toFixed(2)}</b></div><div className="flex justify-between text-emerald-700"><span>Paid</span><b>₹{Number(invoice.paid).toFixed(2)}</b></div><div className="flex justify-between text-rose-700"><span>Due</span><b>₹{Number(invoice.due).toFixed(2)}</b></div></section>
    </article></div>;
}
