'use client';
import {useState} from 'react';
import ActionForm from '@/components/admin/ActionForm';
import {createBill} from './actions';
import BillingCustomer,{Customer} from './BillingCustomer';
import InvoiceItems,{Product,emptyLine} from './InvoiceItems';
import {calculate} from '@/lib/core/src/services/billingMath';
export default function BillingForm({customers,products,date}:{customers:Customer[];products:Product[];date:string}){
 const [mode,setMode]=useState(customers.length?'existing':'new'),[customerId,setCustomerId]=useState(''),[state,setState]=useState('West Bengal'),[lines,setLines]=useState([emptyLine(0)]),[paid,setPaid]=useState(0),[advance,setAdvance]=useState(true);
 const customer=mode==='existing'?customers.find(c=>c.id===customerId):null;let total=0,taxable=0,tax=0;
 try{const result=calculate(lines.filter(x=>x.productId),state.trim().toLowerCase()==='west bengal');total=result.total;taxable=result.taxable;tax=result.cgst+result.sgst+result.igst;}catch{}
 const credit=advance?Math.min(Number(customer?.advance_balance||0),Math.max(0,total-paid)):0;
 return <ActionForm action={createBill} label="Create invoice"><BillingCustomer customers={customers} mode={mode} setMode={setMode} customerId={customerId} setCustomerId={setCustomerId} onState={setState}/><section className="grid gap-4 rounded-2xl border bg-white p-5 md:grid-cols-3"><label className="text-sm font-bold">Our GSTIN (optional)<input name="sellerGstin" maxLength={15} placeholder="MAA LAXMI HARDWARE GSTIN" className="mt-2 w-full rounded-xl border p-3 text-base font-normal"/></label><label className="text-sm font-bold">Invoice date<input name="invoiceDate" type="date" required defaultValue={date} className="mt-2 w-full rounded-xl border p-3 text-base"/></label><label className="text-sm font-bold">Payment method<select name="paymentMethod" className="mt-2 w-full rounded-xl border p-3 text-base"><option>CASH</option><option>UPI</option><option>BANK</option><option>CARD</option></select></label></section><InvoiceItems products={products} lines={lines} setLines={setLines}/><section className="grid gap-5 rounded-2xl border bg-white p-5 md:grid-cols-2"><div className="space-y-4"><label className="block text-sm font-bold">Amount received now ₹<input name="paid" type="number" min="0" max={total||undefined} step="0.01" value={paid} onChange={e=>setPaid(Number(e.target.value))} className="mt-2 w-full rounded-xl border p-3 text-base"/></label><label className="block text-sm font-bold">Payment reference<input name="paymentReference" className="mt-2 w-full rounded-xl border p-3 text-base"/></label><label className="block text-sm font-bold">Notes<textarea name="notes" className="mt-2 w-full rounded-xl border p-3 text-base"/></label><label className="flex items-center gap-3 text-sm"><input type="checkbox" name="useAdvance" checked={advance} onChange={e=>setAdvance(e.target.checked)}/>Apply available customer advance ({Number(customer?.advance_balance||0).toFixed(2)})</label></div><div aria-live="polite" className="space-y-3 rounded-xl bg-slate-50 p-5 text-base">{[['Taxable amount',taxable],['GST',tax],['Grand total (rounded)',total],['Received now',paid],['Customer advance used',credit],['Balance due',Math.max(0,total-paid-credit)]].map(([label,value])=><div key={label} className="flex justify-between gap-4"><span>{label}</span><b>₹{Number(value).toFixed(2)}</b></div>)}</div></section></ActionForm>;
}
