'use client';
import {useState} from 'react';
export type Product={id:string;name:string;sku:string;selling_price:string;gst_rate:string;unit_abbreviation?:string;unit_name?:string;quantity_on_hand:string};
export type Line={key:number;productId:string;quantity:number;unitPrice:number;discount:number;gstRate:number;query:string};
export const emptyLine=(key:number):Line=>({key,productId:'',quantity:1,unitPrice:0,discount:0,gstRate:0,query:''});
export default function InvoiceItems({products,lines,setLines}:{products:Product[];lines:Line[];setLines:(v:Line[])=>void}){
 const [next,setNext]=useState(1);function patch(key:number,fields:Partial<Line>){setLines(lines.map(x=>x.key===key?{...x,...fields}:x));}
 return <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="font-bold">Invoice items</h2><button type="button" onClick={()=>{setLines([...lines,emptyLine(next)]);setNext(next+1);}} className="rounded-lg bg-slate-100 px-4 py-2 text-sm font-bold text-[#07527f]">+ Add product line</button></div><div className="space-y-4">{lines.map((line,index)=>{const p=products.find(p=>p.id===line.productId),hits=line.query&&!p?products.filter(p=>`${p.name} ${p.sku}`.toLowerCase().includes(line.query.toLowerCase())).slice(0,10):[];return <div key={line.key} className="rounded-xl border p-4"><div className="flex items-center justify-between"><b>Item {index+1}</b>{lines.length>1&&<button type="button" onClick={()=>setLines(lines.filter(x=>x.key!==line.key))} className="text-sm font-bold text-rose-700">Remove</button>}</div><input type="hidden" name="productId" value={line.productId}/><div className="relative mt-3"><label className="text-sm font-bold">Product name or SKU<input required aria-label={`Product ${index+1}`} value={line.query} onChange={e=>patch(line.key,{query:e.target.value,productId:''})} placeholder="Search products" autoComplete="off" className="mt-2 w-full rounded-xl border p-3 text-base font-normal"/></label>{line.query&&!p&&<div className="absolute z-20 max-h-64 w-full overflow-auto rounded-xl border bg-white shadow-xl">{hits.map(p=><button key={p.id} type="button" onClick={()=>patch(line.key,{query:p.name,productId:p.id,unitPrice:Number(p.selling_price),gstRate:Number(p.gst_rate)})} className="block w-full border-b p-3 text-left text-base hover:bg-sky-50"><b>{p.name}</b><span className="block text-sm text-slate-600">{p.sku} · ₹{Number(p.selling_price).toFixed(2)} · Stock {p.quantity_on_hand} {p.unit_abbreviation}</span></button>)}{!hits.length&&<p className="p-3 text-sm">No matching product. Add it under Products & Inventory.</p>}</div>}</div><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4">{[['quantity','qty',`Quantity (${p?.unit_abbreviation||p?.unit_name||'units'})`,'0.001','0.001'],['unitPrice','price','Rate ₹','0','0.01'],['discount','discount','Discount %','0','0.01'],['gstRate','gst','GST %','0','0.01']].map(([field,name,label,min,step])=><label key={field} className="text-sm font-bold">{label}<input name={name} type="number" required min={min} max={['discount','gstRate'].includes(field)?100:undefined} step={step} value={line[field as keyof Line]} onChange={e=>patch(line.key,{[field]:Number(e.target.value)})} className="mt-2 w-full rounded-xl border p-3 text-base font-normal"/></label>)}</div></div>;})}</div></section>;
}
