import { getApp } from '@/lib/db';
import { requireAdmin } from '@/lib/session';
import { createBill } from './actions';

export default async function BillingPage(){
  await requireAdmin(); const app=await getApp(); const customers=await app.customerBillingService.listCustomers(); const products=await app.customerBillingService.getProducts();
  return <div className="space-y-5">
    <section className="rounded-2xl bg-[#062f50] p-5 text-white"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-sky-200">Phase 2 · GST Billing</p><h1 className="mt-1 text-2xl font-black">Create Tax Invoice</h1><p className="mt-1 text-sm text-slate-200">GST calculation, payment entry and customer due tracking.</p></section>
    <form action={createBill} className="space-y-5">
      <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-3"><label className="text-xs font-bold text-slate-600">Customer<select name="customerId" className="mt-1 w-full rounded-xl border p-3 text-sm"><option value="">Walk-in customer</option>{customers.map((c:any)=><option key={c.id} value={c.id}>{c.name}{c.phone?` · ${c.phone}`:''}</option>)}</select></label><label className="text-xs font-bold text-slate-600">Invoice date<input name="invoiceDate" type="date" defaultValue={new Date().toISOString().slice(0,10)} className="mt-1 w-full rounded-xl border p-3 text-sm"/></label><label className="text-xs font-bold text-slate-600">Payment method<select name="paymentMethod" className="mt-1 w-full rounded-xl border p-3 text-sm"><option>CASH</option><option>UPI</option><option>BANK</option><option>CARD</option><option>CREDIT</option></select></label></div></section>
      <section className="overflow-x-auto rounded-2xl border bg-white shadow-sm"><div className="border-b px-5 py-4"><h2 className="font-bold">Invoice items</h2><p className="text-xs text-slate-500">Add up to 5 items per bill. GST is calculated from the product rate.</p></div><table className="w-full min-w-[900px] text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-3 py-3 text-left">Product</th><th>Qty</th><th>Price</th><th>Discount %</th><th>GST %</th></tr></thead><tbody>{[0,1,2,3,4].map(i=><tr key={i} className="border-t"><td className="px-3 py-3"><select name={`productId${i}`} className="w-full rounded-lg border p-2"><option value="">— Select product —</option>{products.map((p:any)=><option key={p.id} value={p.id}>{p.name} · ₹{Number(p.selling_price||0).toFixed(2)}</option>)}</select></td><td><input name={`qty${i}`} type="number" min="0.01" step="0.01" defaultValue="1" className="w-20 rounded-lg border p-2"/></td><td><input name={`price${i}`} type="number" min="0" step="0.01" placeholder="Auto" className="w-28 rounded-lg border p-2"/></td><td><input name={`discount${i}`} type="number" min="0" max="100" step="0.01" defaultValue="0" className="w-24 rounded-lg border p-2"/></td><td><input name={`gst${i}`} type="number" min="0" max="100" step="0.01" placeholder="Product" className="w-24 rounded-lg border p-2"/></td></tr>)}</tbody></table></section>
      <section className="grid gap-3 rounded-2xl border bg-white p-5 shadow-sm md:grid-cols-3"><label className="text-xs font-bold text-slate-600">Amount paid<input name="paid" type="number" min="0" step="0.01" defaultValue="0" className="mt-1 w-full rounded-xl border p-3 text-sm"/></label><label className="text-xs font-bold text-slate-600">Payment reference<input name="paymentReference" placeholder="UPI/transaction ref" className="mt-1 w-full rounded-xl border p-3 text-sm"/></label><label className="text-xs font-bold text-slate-600">Notes<textarea name="notes" className="mt-1 w-full rounded-xl border p-3 text-sm"/></label></section>
      <button className="w-full rounded-xl bg-[#07527f] px-5 py-3.5 text-sm font-black text-white shadow-lg hover:bg-[#063f60]">Create GST Invoice →</button>
    </form>
  </div>;
}
