import Link from 'next/link';
import { getApp } from '@/lib/db';
import { requireAdmin } from '@/lib/session';

const money=(v:any)=>`₹${Number(v||0).toFixed(2)}`;
export default function ReportsPage({searchParams}:{searchParams?:{q?:string;status?:string;from?:string;to?:string}}){
 requireAdmin(); const svc=getApp().customerBillingService;
 const q=String(searchParams?.q||''),status=String(searchParams?.status||''),from=String(searchParams?.from||''),to=String(searchParams?.to||'');
 const today=svc.salesSummary('day'); const month=svc.salesSummary('month'); const invoices=svc.searchInvoices({q,status,from,to,limit:200}); const outstanding=svc.outstandingReport(); const stockSales=svc.stockVsSalesReport();
 return <div className="space-y-5">
  <section className="rounded-2xl bg-[#062f50] p-5 text-white"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-sky-200">Phase 2 · Sales intelligence</p><h1 className="mt-1 text-2xl font-black">Sales & Reports</h1><p className="mt-1 text-sm text-slate-200">Sales history, collections, dues and stock movement in one place.</p></section>
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Today Sales',today.sales],['Cash',today.cash],['UPI',today.upi],['Credit / Due',today.due]].map(([l,v])=><div key={String(l)} className="rounded-2xl border bg-white p-4 shadow-sm"><p className="text-xs font-bold uppercase text-slate-500">{l}</p><p className="mt-2 text-2xl font-black text-[#07527f]">{money(v)}</p></div>)}</section>
  <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-bold">Daily & monthly overview</h2><p className="text-xs text-slate-500">Current calendar period</p></div><div className="text-right text-sm"><b>This month:</b> {money(month.sales)} · {month.bills} bills · Due {money(month.due)}</div></div></section>
  <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold">Invoice search & history</h2><form className="mt-3 grid gap-2 md:grid-cols-5"><input name="q" defaultValue={q} placeholder="Invoice / customer / phone" className="rounded-xl border p-2.5 text-sm"/><select name="status" defaultValue={status} className="rounded-xl border p-2.5 text-sm"><option value="">All status</option><option>PAID</option><option>PARTIAL</option><option>UNPAID</option></select><input name="from" type="date" defaultValue={from} className="rounded-xl border p-2.5 text-sm"/><input name="to" type="date" defaultValue={to} className="rounded-xl border p-2.5 text-sm"/><button className="rounded-xl bg-[#07527f] px-4 py-2.5 text-sm font-bold text-white">Search</button></form><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-3">Invoice</th><th className="p-3">Date</th><th className="p-3">Customer</th><th className="p-3 text-right">Total</th><th className="p-3 text-right">Paid</th><th className="p-3 text-right">Due</th><th className="p-3">Status</th></tr></thead><tbody className="divide-y">{invoices.map((i:any)=><tr key={i.id}><td className="p-3 font-semibold"><Link className="text-[#07527f] hover:underline" href={`/admin/billing/${i.id}`}>{i.invoice_no}</Link></td><td className="p-3">{i.invoice_date}</td><td className="p-3">{i.customer_name||'Walk-in'}</td><td className="p-3 text-right">{money(i.total)}</td><td className="p-3 text-right">{money(i.paid)}</td><td className="p-3 text-right font-bold text-rose-700">{money(i.due)}</td><td className="p-3">{i.payment_status}</td></tr>)}</tbody></table></div></section>
  <section className="grid gap-5 lg:grid-cols-2"><div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-4"><h2 className="font-bold">Outstanding dues</h2></div><div className="max-h-96 overflow-auto"><table className="w-full text-sm"><tbody className="divide-y">{outstanding.map((c:any)=><tr key={c.id}><td className="p-3"><b>{c.name}</b><div className="text-xs text-slate-500">{c.phone||'No phone'}</div></td><td className="p-3 text-right font-bold text-rose-700">{money(c.total_due)}</td></tr>)}</tbody></table></div></div><div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-4"><h2 className="font-bold">Stock vs sales</h2></div><div className="max-h-96 overflow-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3 text-left">Product</th><th className="p-3 text-right">Sold</th><th className="p-3 text-right">Stock</th></tr></thead><tbody className="divide-y">{stockSales.map((p:any)=><tr key={p.id}><td className="p-3"><b>{p.name}</b><div className="text-xs text-slate-500">{p.sku}</div></td><td className="p-3 text-right">{Number(p.qty_sold||0)}</td><td className="p-3 text-right font-bold">{Number(p.quantity_on_hand||0)}</td></tr>)}</tbody></table></div></div></section>
 </div>;
}
